try{
    throw "Esse Ã© um erro que eu criei"
}
catch(aaa){
    console.log("Ocorreu erro");
    console.error(aaa);
}